version: "3.3"

services:

    backend:
        build:
            context: ./backend
        volumes:
            - ./backend:/app
            # - /etc/localtime:/etc/localtime:ro
        ports:
            - "3000:3000"
        # env_file:
        #     - ./backend/.env
        restart: always
        # depends_on: 
        #     - postgres