version: "3.3"

services:
    backend:
        build:
            context: ./backend
        volumes:
            - ./backend:/app
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "3000:3000"
        networks:
            - jenkins-node-network
        # env_file:
        #     - ./backend/.env
        restart: always
        depends_on: 
            - postgres
    postgres:
        image: postgres:12-alpine
        # volumes:
            # - ./backend/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
        environment:
            POSTGRES_USER: henry
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: jenkins_node_dev
        networks:
            - jenkins-node-network
        restart: always

networks:
    jenkins-node-network: