name: Hello
on: push

jobs:
  say-hi:
    name: Say Hello
    runs-on: ubuntu-18.04
    steps:
      - name: Hello  There
        run: echo 'Hello  There'

      - name: Show Path
        shell: bash
        run: echo $PWD